projects:
  simpleapp:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: 272aurjupzdrdkiz3jhv4b52j4
      endpoints:
        prod: >-
          https://54dy3tb6nbfgvdkjpmj4cvette.appsync-api.us-west-2.amazonaws.com/graphql
