// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "simpleapp-20190102163944-hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://simpleapp-20190102163944-hostingbucket.s3-website-us-west-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-west-2:95290d91-44e4-4b28-8e7d-db15af2034db",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_7Aixwx5s8",
    "aws_user_pools_web_client_id": "orogbakf9ltemk9ks4dni80qp",
    "aws_appsync_graphqlEndpoint": "https://54dy3tb6nbfgvdkjpmj4cvette.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
